SELECT EM.FIRST_NAME, 
       EM.LAST_NAME, 
       EM.PHONE_NUMBER, 
       EM.HIRE_DATE,
       J.JOB_TITLE,
       SALARY, 
       NVL(DP.DEPARTMENT_NAME, 'DEP NOT DEFINED') AS DEPARTMENT_NAME, 
       NVL(DP.LOCATION_ID,0) AS LOCATION_ID,
       NVL(CT.CITY,'NOT DEFINED') AS CITY,
       NVL(CT.STREET_ADDRESS,'NOT DEFINED') AS STREET_ADDRESS,
       NVL(CT.POSTAL_CODE,'NOT DEFINED') AS POSTAL_CODE
FROM HR.EMPLOYEES EM
LEFT JOIN HR.DEPARTMENTS DP
ON EM.DEPARTMENT_ID = DP.DEPARTMENT_ID
JOIN HR.JOBS J
ON EM.JOB_ID = J.JOB_ID
LEFT JOIN HR.LOCATIONS CT
ON DP.LOCATION_ID = CT.LOCATION_ID
ORDER BY EM.EMPLOYEE_ID;
