SELECT EM.FIRST_NAME, 
       EM.HIRE_DATE, 
       EM.SALARY, 
       CASE 
        WHEN EM.SALARY BETWEEN 2000 AND 7999 THEN 'LOW_SALARY'
        WHEN EM.SALARY BETWEEN 8000 AND 13000 THEN 'MIDDLE_SALARY'
        --WHEN EM.SALARY BETWEEN 13001 AND 30000 THEN 'HIGHT_SALARY'
         ELSE 'HIGHT_SALARY' 
          END AS LEVEL_SALARY
FROM HR.EMPLOYEES EM
ORDER BY 3;
